### Numpy
***

Numpy is a fundamental library for scientific computing in Python.It provides support for arrays and matrices,along with a collection of mathematical function to operate on these data structures in this lesson we will cover the basics of numpyy ,focusing on arrays and vectorised operations 

In [2]:
import numpy as np 
import pandas as pd

In [4]:
#create array using numpy
#create a 1d array 

arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
#1D array
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5)   #1 row and 5coloumns 


array([[1, 2, 3, 4, 5]])

In [ ]:
#2 D array 
arr2 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2.shape)
print(arr2)


(2, 5)
[[1 2 3 4 5]
 [2 3 4 5 6]]


In [ ]:
np.arange(0,10,2).reshape(5,1)
#between 0 to 10 with steps of 2 then reshaping it to 5,1 matrix

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [ ]:

np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
#identity matrix 
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])

print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)

#attributes of numpy array


[[1 2 3]
 [4 5 6]]
(2, 3)
2
6
int64
8


In [18]:
##numpy vectoized operations 
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

#elemet wise addition

print ('Addition:',arr1 +arr2)

#element wise subtraction 

print('substraction:',arr1-arr2)

#element wise multiplcation

print('Multiplication:', arr1*arr2)

#element wise division

print('Divison:',arr1/arr2)



Addition: [11 22 33 44 55]
substraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Divison: [0.1 0.1 0.1 0.1 0.1]


In [23]:
#Universal Function 
arr = np.array([2,3,4,5,6])
#square root
print(np.sqrt(arr))

#exponential 
print(np.exp(arr))

##sine
print(np.sin(arr))

#log 
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [25]:
## array slicing and indexing 
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print('Array:\n', arr)


Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [38]:
#
print(arr[0,0])
print(arr[0])
print(arr[1:])

1
[1 2 3 4]
[[ 5  6  7  8]
 [ 9 10 11 12]]


In [37]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])