### Numpy
***

Numpy is a fundamental library for scientific computing in Python.It provides support for arrays and matrices,along with a collection of mathematical function to operate on these data structures in this lesson we will cover the basics of numpyy ,focusing on arrays and vectorised operations 

In [2]:
import numpy as np 
import pandas as pd

In [4]:
#create array using numpy
#create a 1d array 

arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
#1D array
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5)   #1 row and 5coloumns 


array([[1, 2, 3, 4, 5]])

In [ ]:
#2 D array 
arr2 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2.shape)
print(arr2)


(2, 5)
[[1 2 3 4 5]
 [2 3 4 5 6]]


In [ ]:
np.arange(0,10,2).reshape(5,1)
#between 0 to 10 with steps of 2 then reshaping it to 5,1 matrix

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [ ]:

np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
#identity matrix 
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])

print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)

#attributes of numpy array


[[1 2 3]
 [4 5 6]]
(2, 3)
2
6
int64
8


In [18]:
##numpy vectoized operations 
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

#elemet wise addition

print ('Addition:',arr1 +arr2)

#element wise subtraction 

print('substraction:',arr1-arr2)

#element wise multiplcation

print('Multiplication:', arr1*arr2)

#element wise division

print('Divison:',arr1/arr2)



Addition: [11 22 33 44 55]
substraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Divison: [0.1 0.1 0.1 0.1 0.1]


In [23]:
#Universal Function 
arr = np.array([2,3,4,5,6])
#square root
print(np.sqrt(arr))

#exponential 
print(np.exp(arr))

##sine
print(np.sin(arr))

#log 
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [25]:
## array slicing and indexing 
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print('Array:\n', arr)


Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [38]:
#
print(arr[0,0])
print(arr[0])
print(arr[1:])

1
[1 2 3 4]
[[ 5  6  7  8]
 [ 9 10 11 12]]


In [37]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [3]:
#statistccal concepts -- normalization 
#to have mean and standard deviation of data
data = np.array([1,2,3,4,5])

#calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

#normalize the data 
normalized_data = (data-mean) / std_dev
print("normalised data : ",normalized_data)


normalised data :  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [5]:
data = np.array([1,2,3,4,5,6,7,8,9,10])
#mean

mean=np.mean(data)
print("Mean :",mean)

#median
median = np.median(data)
print("median:",median)

#standard deviation
std_dev=np.std(data)
print('standard deviation:',std_dev)

#Variance 
variance = np.var(data)
print("variance:",variance)

Mean : 5.5
median: 5.5
standard deviation: 2.8722813232690143
variance: 8.25


In [6]:
#logical operartion

data = np.array([1,2,3,4,5,6,7,8,9,10])
data[data>5]

array([ 6,  7,  8,  9, 10])

In [7]:
data[(data>5) & (data<=8)]

array([6, 7, 8])

### Pandas-Dataframe and series

pandas is a powerful data manipulation library in python,widely used for data analysis and data cleaning.it provides two primary data structures:Series and Dataframe a series is a one-dimensional array-like object, while dataframe is a two-dimensional, size mutable and potentially hetergenous tabular data strucutre with labeled axes(rows and columns)

In [14]:
##series 
#A pandas series is a one dimensional array like object that can hold my data type. it is simillar

import pandas as pd
data =[1,2,3,4,5,6]

series = pd.Series(data)

print("Series \n",series)
print(type(series))


Series 
 0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64
<class 'pandas.core.series.Series'>


In [15]:
#create series from dictionary
data ={"a":1,"b":2,"c":3}
series_dict=pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64


In [16]:
data = [10,20,30]
index = ['a','b','c']
pd.Series(data,index=index)


a    10
b    20
c    30
dtype: int64

In [20]:
#Dataframe
data ={'name':['yash','john','jack'],
       'age':[12,12,1232],
       'city':['bangalore','newyork','florid']
       }
dta=pd.DataFrame(data)
print(dta)

   name   age       city
0  yash    12  bangalore
1  john    12    newyork
2  jack  1232     florid


In [23]:
#create a dataframene from a list of dictionaries 
data =[{'name':'yash','age':22,'City':'Bangalore'},
       {'name':'krish','age':32,'City':'New York'},
       {'name':'john','age':26,'City':'Florida'}
       ]

df=pd.DataFrame(data)
print(df)
print(type(df))

    name  age       City
0   yash   22  Bangalore
1  krish   32   New York
2   john   26    Florida
<class 'pandas.core.frame.DataFrame'>


In [ ]:
df=pd.read_csv('sales_data.csv')
print(df.head(5))
df.tail(5)


In [24]:
df

,name,age,City
0,yash,22,Bangalore
1,krish,32,New York
2,john,26,Florida


In [25]:
df['name']

0     yash
1    krish
2     john
Name: name, dtype: object

In [26]:
df.loc[0][0 ]

/tmp/ipykernel_4397/1368262103.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.loc[0][0 ]


'yash'

In [27]:
df.at[0,'age']

np.int64(22)

In [28]:
#accesssing specifiec path of elementdf
df.iat[2,2]

'Florida'

In [29]:
#data manipulation with dataframe

df


,name,age,City
0,yash,22,Bangalore
1,krish,32,New York
2,john,26,Florida


In [31]:
df['Salary']=[50000,76000,80000]
df

,name,age,City,Salary
0,yash,22,Bangalore,50000
1,krish,32,New York,76000
2,john,26,Florida,80000


In [32]:
#remove a column 
df.drop('Salary',axis=1) #by default axis value is zero (it checks the row values)

,name,age,City
0,yash,22,Bangalore
1,krish,32,New York
2,john,26,Florida


In [ ]:
df #drop didnt do the permanent change in the table in order to make permanent changes use "Inplace"


,name,age,City,Salary
0,yash,22,Bangalore,50000
1,krish,32,New York,76000
2,john,26,Florida,80000


In [34]:
df.drop('Salary',axis = 1,inplace=True )

In [35]:
df

,name,age,City
0,yash,22,Bangalore
1,krish,32,New York
2,john,26,Florida


In [ ]:
#add age to the coloumns
df['age']=df['age']+2
df

,name,age,City
0,yash,24,Bangalore
1,krish,34,New York
2,john,28,Florida


In [38]:
df.drop(0)

,name,age,City
1,krish,34,New York
2,john,28,Florida


In [40]:
print('Data types:\n',df.dtypes)
print("statistical summary:\n",df.describe())


Data types:
 name    object
age      int64
City    object
dtype: object
statistical summary:
              age
count   3.000000
mean   28.666667
std     5.033223
min    24.000000
25%    26.000000
50%    28.000000
75%    31.000000
max    34.000000


### Data analysis and manipulation in python
***

data manipulation and analysis are key tasks in any data science or data analysis project,pandas provide a wide range of functions for data manipulation and analysis, making it easierto clean,transform,and extract
insights from data.

In [41]:
df=pd.read_csv('data.csv')
df

,Date,Category,Value,Product,Sales,Region
0,2023-01-01,A,28.0,Product1,754.0,East
1,2023-01-02,B,39.0,Product3,110.0,North
2,2023-01-03,C,32.0,Product2,398.0,East
3,2023-01-04,B,8.0,Product1,522.0,East
4,2023-01-05,B,26.0,Product3,869.0,North
5,2023-01-06,B,54.0,Product3,192.0,West
6,2023-01-07,A,16.0,Product1,936.0,East
7,2023-01-08,C,89.0,Product1,488.0,West
8,2023-01-09,C,37.0,Product3,772.0,West
9,2023-01-10,A,22.0,Product2,834.0,West


In [42]:
df.head(5)

,Date,Category,Value,Product,Sales,Region
0,2023-01-01,A,28.0,Product1,754.0,East
1,2023-01-02,B,39.0,Product3,110.0,North
2,2023-01-03,C,32.0,Product2,398.0,East
3,2023-01-04,B,8.0,Product1,522.0,East
4,2023-01-05,B,26.0,Product3,869.0,North


In [43]:
df.tail(5)

,Date,Category,Value,Product,Sales,Region
45,2023-02-15,B,99.0,Product2,599.0,West
46,2023-02-16,B,6.0,Product1,938.0,South
47,2023-02-17,B,69.0,Product3,143.0,West
48,2023-02-18,C,65.0,Product3,182.0,North
49,2023-02-19,C,11.0,Product3,708.0,North


In [44]:
df.describe()

,Value,Sales
count,47.000000,46.000000
mean,51.744681,557.130435
std,29.050532,274.598584
min,2.000000,108.000000
25%,27.500000,339.000000
50%,54.000000,591.500000
75%,70.000000,767.500000
max,99.000000,992.000000


In [45]:
df.dtypes

Date         object
Category     object
Value       float64
Product      object
Sales       float64
Region       object
dtype: object

In [49]:
#handling missing values

df.isnull().any(axis=0)

Date        False
Category    False
Value        True
Product     False
Sales        True
Region      False
dtype: bool

In [50]:
df.isnull().sum()

Date        0
Category    0
Value       3
Product     0
Sales       4
Region      0
dtype: int64

In [52]:
df_filled=df.fillna(0)

In [55]:
##FILLED missing values with the mean of the coloumn
df['Sales_fillNA']=df['Sales'].fillna(df['Sales'].mean())
df.head(5)

,Date,Category,Value,Product,Sales,Region,Sales_fillNA
0,2023-01-01,A,28.0,Product1,754.0,East,754.0
1,2023-01-02,B,39.0,Product3,110.0,North,110.0
2,2023-01-03,C,32.0,Product2,398.0,East,398.0
3,2023-01-04,B,8.0,Product1,522.0,East,522.0
4,2023-01-05,B,26.0,Product3,869.0,North,869.0


In [56]:
df.dtypes

Date             object
Category         object
Value           float64
Product          object
Sales           float64
Region           object
Sales_fillNA    float64
dtype: object

In [57]:
df.isnull().sum()

Date            0
Category        0
Value           3
Product         0
Sales           4
Region          0
Sales_fillNA    0
dtype: int64

In [61]:
#renaming coloumns
df=df.rename(columns={'Date':'Sale Date'})
df.head()

,Sale Date,Category,Value,Product,Sales,Region,Sales_fillNA
0,2023-01-01,A,28.0,Product1,754.0,East,754.0
1,2023-01-02,B,39.0,Product3,110.0,North,110.0
2,2023-01-03,C,32.0,Product2,398.0,East,398.0
3,2023-01-04,B,8.0,Product1,522.0,East,522.0
4,2023-01-05,B,26.0,Product3,869.0,North,869.0


In [ ]:
#changes datatypes
df['Value_new']=df['Value'].astype(float)

,Sale Date,Category,Value,Product,Sales,Region,Sales_fillNA,Value_new
0,2023-01-01,A,28.0,Product1,754.0,East,754.0,28.0
1,2023-01-02,B,39.0,Product3,110.0,North,110.0,39.0
2,2023-01-03,C,32.0,Product2,398.0,East,398.0,32.0
3,2023-01-04,B,8.0,Product1,522.0,East,522.0,8.0
4,2023-01-05,B,26.0,Product3,869.0,North,869.0,26.0


In [63]:
df['Value_new']=df['Value'].fillna(df['Value']).astype(float)
df.head()

,Sale Date,Category,Value,Product,Sales,Region,Sales_fillNA,Value_new
0,2023-01-01,A,28.0,Product1,754.0,East,754.0,28.0
1,2023-01-02,B,39.0,Product3,110.0,North,110.0,39.0
2,2023-01-03,C,32.0,Product2,398.0,East,398.0,32.0
3,2023-01-04,B,8.0,Product1,522.0,East,522.0,8.0
4,2023-01-05,B,26.0,Product3,869.0,North,869.0,26.0


In [65]:
df['New Value']= df['Value'].apply(lambda x:x*2)
df.head()

,Sale Date,Category,Value,Product,Sales,Region,Sales_fillNA,Value_new,New Value
0,2023-01-01,A,28.0,Product1,754.0,East,754.0,28.0,56.0
1,2023-01-02,B,39.0,Product3,110.0,North,110.0,39.0,78.0
2,2023-01-03,C,32.0,Product2,398.0,East,398.0,32.0,64.0
3,2023-01-04,B,8.0,Product1,522.0,East,522.0,8.0,16.0
4,2023-01-05,B,26.0,Product3,869.0,North,869.0,26.0,52.0


In [66]:
##data aggregation and grouping 
df.head()

,Sale Date,Category,Value,Product,Sales,Region,Sales_fillNA,Value_new,New Value
0,2023-01-01,A,28.0,Product1,754.0,East,754.0,28.0,56.0
1,2023-01-02,B,39.0,Product3,110.0,North,110.0,39.0,78.0
2,2023-01-03,C,32.0,Product2,398.0,East,398.0,32.0,64.0
3,2023-01-04,B,8.0,Product1,522.0,East,522.0,8.0,16.0
4,2023-01-05,B,26.0,Product3,869.0,North,869.0,26.0,52.0


In [68]:
grouped_mean = df.groupby('Product')['Value'].mean()
print(grouped_mean)

Product
Product1    46.214286
Product2    52.800000
Product3    55.166667
Name: Value, dtype: float64


In [69]:
grouped_sum=df.groupby(['Product','Region'])['Value'].sum()
print(grouped_sum)

Product   Region
Product1  East      292.0
          North       9.0
          South     100.0
          West      246.0
Product2  East       56.0
          North     127.0
          South     181.0
          West      428.0
Product3  East      202.0
          North     203.0
          South     215.0
          West      373.0
Name: Value, dtype: float64


In [70]:
df.groupby(['Product','Region'])['Value'].mean()

Product   Region
Product1  East      41.714286
          North      4.500000
          South     50.000000
          West      82.000000
Product2  East      28.000000
          North     63.500000
          South     60.333333
          West      53.500000
Product3  East      50.500000
          North     40.600000
          South     71.666667
          West      62.166667
Name: Value, dtype: float64

In [72]:
##aggregate multiple functions
grouped_agg=df.groupby('Region')['Value'].agg(['mean','sum','count'])
grouped_agg

,mean,sum,count
Region,,,
East,42.307692,550.0,13
North,37.666667,339.0,9
South,62.000000,496.0,8
West,61.588235,1047.0,17


In [73]:
#Merging and joining Dataframes
df1=pd.DataFrame({'Key':['A','B','C'],'Value1':[1,2,3]})
df2=pd.DataFrame({'Key':['A','B','D'],'Value1':[4,5,6]})

In [74]:
pd.merge(df1,df2,on='Key',how='inner')

,Key,Value1_x,Value1_y
0,A,1,4
1,B,2,5


In [75]:
pd.merge(df1,df2,on='Key',how='outer')

,Key,Value1_x,Value1_y
0,A,1.0,4.0
1,B,2.0,5.0
2,C,3.0,NaN
3,D,NaN,6.0


In [76]:
pd.merge(df1,df2,on='Key',how='left')

,Key,Value1_x,Value1_y
0,A,1,4.0
1,B,2,5.0
2,C,3,NaN


In [78]:
pd.merge(df1,df2,on='Key',how='right')

,Key,Value1_x,Value1_y
0,A,1.0,4
1,B,2.0,5
2,D,NaN,6
